### ISSUE TITLE
Keep receiving TypeNotFound when running in console

### ISSUE THREAD

**Issue by soke1556** [anthonyg-1/PSGraphQL#5] opened 2021-06-28 02:59 UTC
Hey there! I've been running my script using VSCode environment without any issue.

But when I try to run the same scripts using PS console (Task Scheduler) I receive the following issue:

```sh
Unable to find type [Microsoft.PowerShell.Commands.WebRequestSession].
At C:\Users\sebas\Documents\WindowsPowerShell\Modules\PSGraphQL\1.0.10\Functions\Invoke-GraphQLQuery.ps1:144 char:27
+ ... sition = 3)][Microsoft.PowerShell.Commands.WebRequestSession]$WebSess ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...bRequestSession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

Any ideas?

Thanks in advance!

**Comment by anthonyg-1** [comment] 2021-06-28 11:28
Hello, please try the following in order:


1) Before importing the PSGraphQL module, run "Import-Module Microsoft.PowerShell.Utility -Force" then import PSGraphQL and attempt to execute Invoke-GraphQLQuery.
2) From the same computer (as a scheduled task) run Invoke-RestMethod to a known endpoint and let me know the results. This may determine if something is broken regarding the current installation of PowerShell.
3) From a different computer run Invoke-GraphQLQuery (as a scheduled task). This will determine if the issue is isolated to the above machine.
4) Please post the output of $PSVersionTable here.

**Comment by soke1556** [comment] 2021-06-28 11:38
Hey there!

Thanks for your response.

It fails when running Invoke-RestMethod as a scheduled task) (Step 2)

```sh
Invoke-RestMethod : GET query missing.
At line:1 char:1
+ Invoke-RestMethod
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by anthonyg-1** [comment] 2021-06-28 11:47
Sorry I meant Invoke-RestMethod with a URI but I think I know the issue. Can you create a new scheduled task that runs the following in sequence:

Import-Module Microsoft.PowerShell.Utility -Function Invoke-RestMethod -Force
Import-Module PSGraphQLQuery
# ...then your GQL query via:
Invoke-GraphQLQuery -Query <your query> -Uri <your URI>

**Comment by anthonyg-1** [comment] 2021-06-28 13:03
I was able to replicate this issue myself. This has been fixed in v1.1.5. Please get the latest version and let me know if this issue still occurs.

**Closed as completed by anthonyg-1** 2021-06-28 13:03 UTC

**Comment by soke1556** [comment] 2021-06-28 14:18
It works! Thanks!

**Comment by anthonyg-1** [comment] 2021-06-28 14:20
You are very welcome. Please let me know if you experience any other issues.
